auto_save: 15

messages:
  not_enough_permissions: '&cNot enough permissions.'
  reloaded: '&8[&3DailyRewards&8] &fSuccessfully &breloaded configuration&f.'
  claim_status:
    claimed: "&cAlready claimed, come back in {TIME_REMAINING}"
    unclaimed: "&aRight click to claim!"

gui:
  display_name: 'Daily rewards'
  layout:
    - '#########'
    - '         '
    - '  a   b  '
    - '         '
    - '#########'
  items:
    '#':
      display_name: '&f'
      material: 'BLACK_STAINED_GLASS_PANE'
  rewards:
    'a':
      - basic_reward
    'b':
      - vip_reward
      - supervip_reward

rewards:
  basic_reward:
    required_permission: 'dailyrewards.basic'
    cooldown: 86400
    action_list:
      - '[actionbar] &eYou have opened basic daily reward.'
      - '[broadcast] &ePlayer &6{PLAYER} &ehas opened basic daily reward.'
      - '[message] &eYou have opened basic daily reward.'
      - '[player-command] time set day'
      - '[server-command] say Player {PLAYER} has opened basic daily reward.'
      - '[sound] ENTITY_EXPERIENCE_ORB_PICKUP'
      - '[title] &eOpened Daily reward;&6You have opened the basic daily reward.'
    gui:
      claimed:
        material: 'MINECART'
        display_name: '&eBasic Daily Reward'
        lore:
          - ' '
          - ' &fRewards all of our loyal players with'
          - ' &fa small present every day they log in.'
          - ' '
          - ' {CLAIM}'
      unclaimed:
        material: 'CHEST_MINECART'
        display_name: '&eBasic Daily Reward'
        lore:
          - ' '
          - ' &fRewards all of our loyal players with'
          - ' &fa small present every day they log in.'
          - ' '
          - ' {CLAIM}'
  vip_reward:
    required_permission: "dailyrewards.vip"
    cooldown: 86400
    action_list:
      - '[actionbar] &dYou have opened basic daily reward.'
      - '[broadcast] &dPlayer &5{PLAYER} &dhas opened basic daily reward.'
      - '[message] &dYou have opened basic daily reward.'
      - '[player-command] time set day'
      - '[server-command] say Player {PLAYER} has opened basic daily reward.'
      - '[sound] ENTITY_EXPERIENCE_ORB_PICKUP'
      - '[title] &dOpened Daily reward;&5You have opened the basic daily reward.'
    gui:
      claimed:
        material: 'MINECART'
        display_name: '&dVIP Daily Reward'
        lore:
          - ' '
          - ' &fA warm thank to all of our donators that'
          - ' &fallow us to run the server.'
          - ' '
          - ' {CLAIM}'
      unclaimed:
        material: 'CHEST_MINECART'
        display_name: '&dVIP Daily Reward'
        lore:
          - ' '
          - ' &fA warm thank to all of our donators that'
          - ' &fallow us to run the server.'
          - ' '
          - ' {CLAIM}'

  supervip_reward:
    required_permission: "dailyrewards.supervip"
    cooldown: 86400
    action_list:
      - '[actionbar] &3You have opened basic daily reward.'
      - '[broadcast] &3Player &b{PLAYER} &3has opened basic daily reward.'
      - '[message] &3You have opened basic daily reward.'
      - '[player-command] time set day'
      - '[server-command] say Player {PLAYER} has opened basic daily reward.'
      - '[sound] ENTITY_EXPERIENCE_ORB_PICKUP'
      - '[title] &3Opened Daily reward;&bYou have opened the basic daily reward.'
    gui:
      claimed:
        material: 'MINECART'
        display_name: '&3SuperVIP Daily Reward'
        lore:
          - ' '
          - ' &fA warm thank to all of our donators that'
          - ' &fallow us to run the server.'
          - ' '
          - ' {CLAIM}'
      unclaimed:
        material: 'CHEST_MINECART'
        display_name: '&3SuperVIP Daily Reward'
        lore:
          - ' '
          - ' &fA warm thank to all of our donators that'
          - ' &fallow us to run the server.'
          - ' '
          - ' {CLAIM}'